### ISSUE TITLE
Marcos To-Do List

### ISSUE THREAD

**Issue by marcosgabriel-smc** [meleu/PartyGears#4]
- [x] My user profile
   - [x]  Edit my gears
       -  [x] Change each attribute
   -  [ ] My Offers as renter
       -  [ ] Edit
       -  [ ] Check Status
       -  [ ] Contact owner
  -  [x] My Offers as owners
       -  [x] Accept/Decline
       -  [ ] Contact renter
- [x]  Acess the profile of the gear owner through the gear show page
  -  [x] View User Name
  -  [x] Acess contact info
  - [x]  List all the users available gears
  -  [ ] List Reviews
