### ISSUE TITLE
Meleu To-Do List

### ISSUE THREAD

**Issue by marcosgabriel-smc** [meleu/PartyGears#5]
- [x] Filtering buttons must comeback to all gears
    - [x] Change view of each button when active
- [ ] Offers
    - [x] After creating an offer, render "offer created"
    - [ ] Block offers from the same user when a request for that time period has already been made
    - [ ] Block offerings for when a previous offer has been accepted
